### PR TITLE
Rebased: sparse data processing functions and readme update

### PR DESCRIPTION
**Pull request by cjh1**
Cherry-pick of #142 commits to fix issues introduced by rebase.

### CODE REVIEW

**Comment by cjh1** [comment]
@ercius If its ok, I may get @psavery to reformat the doc string so they will work with readthedoc if that is ok?

**Comment by ercius** [comment]
@cjh1 For sure!

**Comment by ercius** [comment]
@cjh1 Im happy to rewrite the docstrings to match the reST format. Where should I make the changes? Im not sure how to attach them to this PR. DOo I checkout upstrea/peter and do the changes there on my fork?

**Comment by cjh1** [comment]
@ercius Its ok, @psavery is going todo it. Sorry for the delay.

**Comment by ercius** [comment]
@cjh1 No problem! Things are a little crazy right now. There isn't a rush.

I was just looking into docstrings and it reminded me of this PR. I use Numpy docstrings, but it looks like reST works better for Sphinx.

**Comment by psavery** [comment]
The function docstrings have been reformatted.

**Comment by cjh1** [comment]
@ercius All merged :-)

**Comment by ercius** [comment]
Awesome. Thanks! 

Can we get a new singularity image built?

**Comment by cjh1** [comment]
New image pushed.

**Pull request merged**
