### PR TITLE
Add some missing reqs to requirements-dev

### PR DESCRIPTION
**Pull request by psavery**
These are required in some of the example files.

### CODE REVIEW

**Comment by psavery** [comment]
@cryos We had actually created this file with the intention of putting requirements for the examples in it. The requirement that is already inside, `click`, is also only a requirement for the examples.

Maybe we should move it into the examples dir as `requirements.txt` if that would be better?

**Comment by cjh1** [comment]
@psavery Yes, moving it to the examples directory makes more sense.

**Comment by cryos** [comment]
Completely agree, examples are nice, and we want to avoid making people guess, but they shouldn't be confused with developer requirements which are often more than is needed to simply run the code. I hate encountering packages that attempt to install too much - keep our requirements as lean as we reasonably can.

**Comment by psavery** [comment]
Sounds good, I moved that requirements file into the examples directory.

**Pull request merged**
