### PR TITLE
Prevent copying numpy array electron counting data

### PR DESCRIPTION
**Pull request by cjh1**
Use py::array_t instead.

### CODE REVIEW

**Comment by cjh1** [comment]
Fixed #154

**Comment by cjh1** [comment]
@ercius I updated the jupyter lab image on cori, if you want to try these changes out.

**Comment by ercius** [comment]
@cjh1 This is working. Its just as fast as when the data comes from the counting function. Thanks!

**Comment by cjh1** [comment]
@psavery Could you do a quick review if you get a change?

**Comment by cjh1** [comment]
@psavery Could you review this one as well?

**Pull request merged**
