### PR TITLE
Bump HDF5 build version on the Mac

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by psavery** [comment]
Were these changes specifically for arm64, x86_64, or both?

**Comment by cjh1** [comment]
For both, although I don't have access to a x86_64 mac to test with.

**Review by psavery — APPROVED** [review]
I gave a wheel a quick try on both x86_64 mac and arm64 mac, and it worked on both! Looks good to me!

**Comment by cjh1** [comment]
Thanks @psavery for the review and testing!

**Pull request merged**
