### PR TITLE
Fix remove_flyback algorithm

### PR DESCRIPTION
**Pull request by ercius**
The current algorithm for removing the flyback doe snot properly account for multiple frames per probe position.

This new algorithm is designed to account for that problem.

Its not ready yet. I need to build new stempy version to test it.

### CODE REVIEW

**Comment by ercius** [comment]
This looks like it is working. Can we issue a release candidate with this and the other pull requests? I want to test it a little more thoroughly.

**Comment by cjh1** [comment]
@ercius Sorry for the delayed response. As part of the CI for a PR a wheel is built ( just download the the artifacts ) you can use that for testing. The CI is currently failing because you are removing `scan_positions` and it is still referenced in the version 3 block.

**Comment by ercius** [comment]
@cjh1 Thanks for finding my error. I've added in scan_positions and will grab the artifact to more fully test this new algorithm.

**Comment by ercius** [comment]
@cjh1 I think this is good to merge. Can you take a look?

**Review by cjh1 — APPROVED** [review]
LGTM

**Pull request merged**
