### PR TITLE
Add click as a requirement in requirements-dev.txt

### PR DESCRIPTION
**Pull request by psavery**
We use click in several scripts. Add it as a requirement.

### CODE REVIEW

**Comment by cryos** [comment]
We use it in test scripts, but do we need it for the Python module itself? It would be good to keep the core module requirements really minimal, it is intended first and foremost as a Python module.

**Comment by psavery** [comment]
Okay, yeah I think we can leave it out then. It's mostly just for test scripts. Maybe we can add the extra dev requirements in a `requirements-dev.txt` file?

**Comment by cryos** [comment]
That could be the way to go, I think it is important to keep the main package as lean as reasonable.

**Comment by psavery** [comment]
Done.

**Pull request merged**
