### PR TITLE
Add support for multi frame scans

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@ercius This should fix the issue we are seeing. It certainly does with scan225. The events from any addition frames are now append rather than replacing the previous frame. Note there made be a small performance hit, as we now need to protect that append operation from access by multiple threads, but it shouldn't be too bad. I have push as test image that you can try out: 

```
singularity pull docker://openchemistry/stempy:multi-frame
```

**Comment by cjh1** [comment]
Fixes #176

**Comment by ercius** [comment]
This works! Awesome work. That is super useful. Good to merge.

**Review by psavery — APPROVED** [review]
LGTM

**Comment by ercius** [comment]
Great! Can we update the images? I'll pull it to mothership6

**Comment by cjh1** [comment]
Done, new image is uploaded.

**Pull request merged**
