### PR TITLE
Image number indexes start from one

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by psavery** [comment]
@cjh1 Looks like it is this PR that is causing the seg fault. If I revert master back before this one and compile, it runs fine.

**Comment by psavery** [comment]
Probably because of the `header.imageNumbers.push_back(firstImageNumber + i)` down below... maybe I can fix that.

**Comment by psavery** [comment]
I think I found the cause of the crash. It occurs [here](https://github.com/OpenChemistry/stempy/blob/f7363b38ba1abca180482d7e6b2c1f0b621e04a7/stempy/electron.cpp#L233), because the image numbers no longer start with 0.

**Comment by cjh1** [comment]
@psavery Great debugging, thanks, I will look at pushing a fix.

**Pull request merged**
